### ISSUE TITLE
Having issues on both Python3 and Python2 for different reasons

### ISSUE THREAD

**Issue by adambaskerville** [bnaecker/pygsvd#4]
Firstly, I would like to thank you for making this Python wrapper to a very useful LAPACK routine. I feel this module could be very popular as there have been many people wondering why SciPy has not wrapped this LAPACK routine, moreso why it seemingly never will (judging by comments in the Git repository)

I am having issues with both Python3 and Python2 versions but for different reasons.

The Python3 install works perfectly, but when I import pygsvd I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pygsvd-master/pygsvd.py", line 2, in <module>
    import _gsvd
ImportError: /usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg/_gsvd.cpython-35m-x86_64-linux-gnu.so: undefined symbol: LAPACKE_dggsvd3
```

With Python2, I cannot get it to install. I correctly link the include and library directories as with the Python3 which worked, and I get the following error:

```
Processing /home/pygsvd-master
Requirement already satisfied: numpy>=1.11 in /home/miniconda2/lib/python2.7/site-packages (from pygsvd==0.0.2) (1.14.3)
Building wheels for collected packages: pygsvd
  Running setup.py bdist_wheel for pygsvd ... error
  Complete output from command /home/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-enm4g3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ecobxq --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building '_gsvd' extension
  gcc -pthread -B /home/miniconda2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_LAPACK=1 -I/home/adam/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/include -I/usr/include -I/home/miniconda2/include/python2.7 -c src/_gsvd.c -o build/temp.linux-x86_64-2.7/src/_gsvd.o
  gcc: error: : No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pygsvd
  Running setup.py clean for pygsvd
Failed to build pygsvd
Installing collected packages: pygsvd
  Running setup.py install for pygsvd ... error
    Complete output from command /home/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-enm4g3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d7iN8Z/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build/lib.linux-x86_64-2.7
    copying pygsvd.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_gsvd' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -B /home/miniconda2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_LAPACK=1 -I/home/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/include -I/usr/include -I/home/miniconda2/include/python2.7 -c src/_gsvd.c -o build/temp.linux-x86_64-2.7/src/_gsvd.o
    gcc: error: : No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-enm4g3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d7iN8Z/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-enm4g3/

```
I was wondering if you could offer advice on how tofix these issues?

I raised this as an "issue" on GitHub solely because I thought it the easiest way to communicate. The issue is most likely my ineptitude with the install, and not with your wrapper.

Many thanks

**Comment by bnaecker** [comment]
I'm glad you're interested in the project. I hope it's useful once you get it installed!

The error with Python 3 means that the extension module did not correctly link with your system's LAPACK library. You can verify this by doing the following. Change to the directory `build/temp.linux-x86_64-2.7/src`, and run the command `ldd _gsvd.cpython-35m-x86_64-linux-gnu.so`. One of the lines should list the LAPACK library `liblapacke`, and it should say something about "library not found". 

The directories the setup process looks in for the library are specified in `setup.cfg`, on the line `library_dirs=...`. You can add to that line the location of your library. If you installed it with APT, you can run `dpkg -L liblapacke` to see the files that came with your installation. You're looking for the location of `liblapacke.so` or something very similar to that. It's most likely in `/usr/lib/`, and you can add that to the `library_dirs=...` line.

----------------

The Python 2 error is harder to diagnose. Are you sure all the headers are installed? That would be the `Python.h`, the NumPy headers for your installation of version 2, and `lapacke.h`. You could try just running  `python setup.py build_ext` alone, to see if the problem is during the compilation of the extension library.

**Comment by adambaskerville** [comment]
Thank you for the quick reply. After running the command `ldd _gsvd.cpython-35m-x86_64-linux-gnu.so` I get:

    linux-vdso.so.1 =>  (0x00007ffced533000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d52b70000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f1d5313d000)

So it seems the link to LAPACK is not there as it does not mention it, but I am unsure as to why as running `dpkg -L liblapacke` shows that `liblapacke.so.3` is indeed in `/usr/lib` which I have made sure is in the `.cfg` file. If I go to `/usr/lib` I can see the lapack directory with `liblapacke.so.3` in.

For Python2 I have the newest version of Python-dev installed (2.7.12-1~16.04) so that should cover the `Python.h` header. I can find the Numpy headers by following the directory path that it uses for the build.

Running `python setup.py build_ext` gives:

    building '_gsvd' extension
    gcc -pthread -B /home/miniconda2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2     -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_LAPACK=1 -I/home/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local /include -I/usr/include -I/usr/lib -I/usr/lib/lapack -I/home/miniconda2/include/python2.7 -c  src/_gsvd.c -o build/temp.linux-x86_64-2.7/src/_gsvd.o 
    gcc: error: : No such file or directory
    error: command 'gcc' failed with exit status 1

It seems that it still cannot find the header files but I can see them in the listed directories so I am unsure what it is struggling to find.

**Comment by bnaecker** [comment]
If you have the library correctly installed and its directory is in the config file, the compiler must not be linking to it. What is the exact output of building the extension with Python 3? There should be an argument that looks like `-llapacke`. 

Just for completeness, make sure that `-L/usr/lib` is there too. Also, is there a file that’s just `/usr/lib/liblapacke.so`, or only `/usr/lib/liblapacke.so.3`?

**Comment by adambaskerville** [comment]
The exact output from the Python3 build is (using sudo python3 setup.py install)

    running install
    Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
    /usr/bin/python3 -E -c pass
    TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
    running bdist_egg
    running egg_info
    writing dependency_links to pygsvd.egg-info/dependency_links.txt
    writing requirements to pygsvd.egg-info/requires.txt
    writing pygsvd.egg-info/PKG-INFO
    writing top-level names to pygsvd.egg-info/top_level.txt
    reading manifest file 'pygsvd.egg-info/SOURCES.txt'
    writing manifest file 'pygsvd.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    running build_ext
    building '_gsvd' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_LAPACK=1 -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/local/include -I/usr/local/include -I/usr/include -I/usr/lib/lapack -I/usr/include/python3.5m -c src/_gsvd.c -o build/temp.linux-x86_64-3.5/src/_gsvd.o -DBUILD_WITH_PYTHON3
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/src/_gsvd.o -L/usr/local/lib -L/usr/local/lib -L/usr/lib/lapack -llapacke -o build/lib.linux-x86_64-3.5/_gsvd.cpython-35m-x86_64-linux-gnu.so
    creating build/bdist.linux-x86_64
    creating build/bdist.linux-x86_64/egg
    copying build/lib.linux-x86_64-3.5/pygsvd.py -> build/bdist.linux-x86_64/egg
    copying build/lib.linux-x86_64-3.5/_gsvd.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
    byte-compiling build/bdist.linux-x86_64/egg/pygsvd.py to pygsvd.cpython-35.pyc
    creating stub loader for _gsvd.cpython-35m-x86_64-linux-gnu.so
    byte-compiling build/bdist.linux-x86_64/egg/_gsvd.py to _gsvd.cpython-35.pyc
    creating build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
    zip_safe flag not set; analyzing archive contents...
    __pycache__._gsvd.cpython-35: module references __file__
    creating dist
    creating 'dist/pygsvd-0.0.2-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing pygsvd-0.0.2-py3.5-linux-x86_64.egg
    removing '/usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg' (and everything under it)
    creating /usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg
    Extracting pygsvd-0.0.2-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
    pygsvd 0.0.2 is already the active version in easy-install.pth

    Installed /usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg
    Processing dependencies for pygsvd==0.0.2
    Searching for numpy==1.15.0
    Best match: numpy 1.15.0
    Removing numpy 1.11.0 from easy-install.pth file
    Adding numpy 1.15.0 to easy-install.pth file
    Installing f2py script to /usr/local/bin
    Installing from-template script to /usr/local/bin
    Installing conv-template script to /usr/local/bin

    Using /home/.local/lib/python3.5/site-packages
    Finished processing dependencies for pygsvd==0.0.2

The `-llapacke` argument is there but not `-L/usr/lib`

Both `liblapacke.so` and `liblapacke.so.3` are in /usr/lib/

Many thanks.

**Comment by bnaecker** [comment]
That's really odd. The `-llapacke` flag is specified, which means the compiler should error out if that library cannot be found. Yet it's clearly not linking to the library as we saw with `ldd`. My guess is the build system is a bit off. The compiler must be finding the undefined symbol in `liblapacke`, but then not actually putting that into the list of libraries on which the module depends.

It seems from [this thread](https://www.reddit.com/r/cpp_questions/comments/55vfpd/undefined_symbol_in_extension_module/) that some other people have run into problems building extensions with Anaconda. Can you try running the setup with your system version of Python3? Most likely, that'd be done with the following command: `/usr/bin/python3 setup.py build`. Make sure to then test that it worked by importing the module in the same Python interpreter.

**Comment by adambaskerville** [comment]
Running the command using the system Python3 (in `/usr/bin`) gives:

    running install
    Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
    /usr/bin/python3 -E -c pass
    TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
    running bdist_egg
    running egg_info
    writing dependency_links to pygsvd.egg-info/dependency_links.txt
    writing pygsvd.egg-info/PKG-INFO
    writing top-level names to pygsvd.egg-info/top_level.txt
    writing requirements to pygsvd.egg-info/requires.txt
    reading manifest file 'pygsvd.egg-info/SOURCES.txt'
    writing manifest file 'pygsvd.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    running build_ext
    creating build/bdist.linux-x86_64/egg
    copying build/lib.linux-x86_64-3.5/pygsvd.py -> build/bdist.linux-x86_64/egg
    copying build/lib.linux-x86_64-3.5/_gsvd.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
    byte-compiling build/bdist.linux-x86_64/egg/pygsvd.py to pygsvd.cpython-35.pyc
    creating stub loader for _gsvd.cpython-35m-x86_64-linux-gnu.so
    byte-compiling build/bdist.linux-x86_64/egg/_gsvd.py to _gsvd.cpython-35.pyc
    creating build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pygsvd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
    zip_safe flag not set; analyzing archive contents...
    __pycache__._gsvd.cpython-35: module references __file__
    creating 'dist/pygsvd-0.0.2-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing pygsvd-0.0.2-py3.5-linux-x86_64.egg
    removing '/usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg' (and everything under it)
    creating /usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg
    Extracting pygsvd-0.0.2-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
    pygsvd 0.0.2 is already the active version in easy-install.pth

    Installed /usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg
    Processing dependencies for pygsvd==0.0.2
    Searching for numpy==1.15.0
    Best match: numpy 1.15.0
    Adding numpy 1.15.0 to easy-install.pth file
    Installing f2py script to /usr/local/bin
    Installing conv-template script to /usr/local/bin
    Installing from-template script to /usr/local/bin

    Using /home/.local/lib/python3.5/site-packages
    Finished processing dependencies for pygsvd==0.0.2

which interestingly does not have the `-llapacke` argument. When imported into the same python interpreter (in `/usr/bin/`) The same error is seen:

    ImportError: /usr/local/lib/python3.5/dist-packages/pygsvd-0.0.2-py3.5-linux-x86_64.egg/_gsvd.cpython-35m-x86_64-linux-gnu.so: undefined symbol: LAPACKE_dggsvd3


Using the system Python2 (in `/usr/bin`) gives the same error as before:

    running install
    running bdist_egg
    running egg_info
    writing requirements to pygsvd.egg-info/requires.txt
    writing pygsvd.egg-info/PKG-INFO
    writing top-level names to pygsvd.egg-info/top_level.txt 
    writing dependency_links to pygsvd.egg-info/dependency_links.txt
    reading manifest file 'pygsvd.egg-info/SOURCES.txt'
    writing manifest file 'pygsvd.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    running build_ext
    building '_gsvd' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE_LAPACK=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I/usr/local/include -I/usr/include -I/usr/lib/lapack -I/usr/include/python2.7 -c src/_gsvd.c -o build/temp.linux-x86_64-2.7/src/_gsvd.o 
    x86_64-linux-gnu-gcc: error: : No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

My machine is certainly reluctant to install this module!

**Comment by bnaecker** [comment]
And what if you just try `/usr/bin/python3 build_ext`? What is the output of that? Is the `-llapacke` flag part of the compile command?

Does the extension module (`_gsvd.cpython-35m-x86_64-linux-gnu.so`) have the `LAPACKE_dggsvd3` symbol in it? Is it linked to `/usr/lib/lapacke.so`?

**Comment by adambaskerville** [comment]
When I run the `build_ext` command using `/usr/bin/python3` nothing appears to happen which is odd.

`_gsvd.cpython-35m-x86_64-linux-gnu.so` is in binary so I cannot read it however there are parts which are readable and appears to offer a clue as to what has happened:

    Arrays must be 2-dimensional, numpy.core.multiarray _ARRAY_API _ARRAY_API not found _ARRAY_API is NULL pointer _gsvd Arrays must have the same number of columns

    A LAPACK error occurred: parameter %d was invalid. numpy.core.multiarray failed to import _ARRAY_API is not PyCapsule object module compiled against ABI version 0x%x but this version of numpy is 0x%x module compiled against API version 0x%x but this version of numpy is 0x%x  FATAL: module compiled as unknown endian FATAL: module compiled as little endian, but detected different endianness at runtime

**Comment by bnaecker** [comment]
The file is in Linux’s ELF format, which is how executables and libraries are stored on disk. Those strings are stored inside the are just error messages that some routines will spit out if something goes wrong. They don’t mean the compilation failed, they are data needed when the routines in the library run.


The build didn’t seem to do anything because it only recompiles things if the code has changed. It hasn’t, so nothing happens. You can force it to recompile the library by removing the `build` directory. Please delete the entire `./build/` directory (`rm -r ./build`) and then try the `build_ext` command again.

**Comment by adambaskerville** [comment]
Removing build and then re-running (with system Python3) produces:

    running build_ext
    building '_gsvd' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_LAPACK=1 -I/home/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/include -I/usr/include -I/usr/lib/lapack -I/usr/include/python3.5m -c src/_gsvd.c -o build/temp.linux-x86_64-3.5/src/_gsvd.o -DBUILD_WITH_PYTHON3
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/src/_gsvd.o -L/usr/local/lib -L/usr/local/lib -L/usr/lib/lapack -llapacke -o build/lib.linux-x86_64-3.5/_gsvd.cpython-35m-x86_64-linux-gnu.so

So does have the -llpacke argument. The same error persists when importing `pygsvd` (in system Python3 terminal)

**Comment by bnaecker** [comment]
That looks ok to me, I’m starting to think your system has a somehow messed up installation of LAPACK. 

Does your version of LAPACK actually implement the GSVD? If you run `nm /usr/lib/lapack/liblapacke.so`, does it actually have a symbol named `LAPACKE_dggsvd3`?

I’d also try completely removing this package, recloning from GitHub, reinstalling LAPACK, and then building again. I’m at a loss at this point as to why your machine doesn’t seem to link correctly.

**Comment by adambaskerville** [comment]
I was leaning towards that too so sounds like a good idea. Thank you again for all your help.
